name:                greenclip
version:             1.3.0
synopsis:            Simple clipboard manager to be integrated with rofi
description:         Please see README.md
homepage:            https://github.com/erebe/greenclip#readme
license:             BSD3
author:              Erèbe - Romain GERARD
maintainer:          romain.gerard@erebe.eu
copyright:           2016 Erèbe
category:            Linux Desktop
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - classy-prelude
  - Clipboard
  - text
  - vector
  - binary
  - microlens
  - microlens-mtl
  - directory

executables:
  greenclip:
    source-dirs:      src
    ghc-options:      -Wall -O3 -static
    main:             Main.hs
    ld-options: -static
