name:                mclip
version:             0.1.0.0
synopsis:            Simple project template from stack
description:         Please see README.md
homepage:            https://github.com/githubuser/mclip#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2016 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - classy-prelude
  - Clipboard
  - text
  - vector
  - binary
  - microlens
  - microlens-mtl
  - microlens-th
  - directory
  - comonad

executables:
  mclip:
    source-dirs:      src
    ghc-options:      -O3 -Wall
    ld-options:       -static
    extra-libraries: Xrender xcb X11 Xau Xdmcp
    main:             Main.hs
